apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: test
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32687
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

